%ifndef SYSCALL_ASM
%define SYSCALL_ASM

STDIN                            equ  0
STDOUT                           equ  0

NR_restart_syscall               equ  0
NR_exit                          equ  1
NR_fork                          equ  2
NR_read                          equ  3
NR_write                         equ  4
NR_open                          equ  5
NR_close                         equ  6
NR_waitpid                       equ  7
NR_creat                         equ  8
NR_link                          equ  9
NR_unlink                        equ  10
NR_execve                        equ  11
NR_chdir                         equ  12
NR_time                          equ  13
NR_mknod                         equ  14
NR_chmod                         equ  15
NR_lchown                        equ  16
NR_break                         equ  17
NR_oldstat                       equ  18
NR_lseek                         equ  19
NR_getpid                        equ  20
NR_mount                         equ  21
NR_umount                        equ  22
NR_setuid                        equ  23
NR_getuid                        equ  24
NR_stime                         equ  25
NR_ptrace                        equ  26
NR_alarm                         equ  27
NR_oldfstat                      equ  28
NR_pause                         equ  29
NR_utime                         equ  30
NR_stty                          equ  31
NR_gtty                          equ  32
NR_access                        equ  33
NR_nice                          equ  34
NR_ftime                         equ  35
NR_sync                          equ  36
NR_kill                          equ  37
NR_rename                        equ  38
NR_mkdir                         equ  39
NR_rmdir                         equ  40
NR_dup                           equ  41
NR_pipe                          equ  42
NR_times                         equ  43
NR_prof                          equ  44
NR_brk                           equ  45
NR_setgid                        equ  46
NR_getgid                        equ  47
NR_signal                        equ  48
NR_geteuid                       equ  49
NR_getegid                       equ  50
NR_acct                          equ  51
NR_umount2                       equ  52
NR_lock                          equ  53
NR_ioctl                         equ  54
NR_fcntl                         equ  55
NR_mpx                           equ  56
NR_setpgid                       equ  57
NR_ulimit                        equ  58
NR_oldolduname                   equ  59
NR_umask                         equ  60
NR_chroot                        equ  61
NR_ustat                         equ  62
NR_dup2                          equ  63
NR_getppid                       equ  64
NR_getpgrp                       equ  65
NR_setsid                        equ  66
NR_sigaction                     equ  67
NR_sgetmask                      equ  68
NR_ssetmask                      equ  69
NR_setreuid                      equ  70
NR_setregid                      equ  71
NR_sigsuspend                    equ  72
NR_sigpending                    equ  73
NR_sethostname                   equ  74
NR_setrlimit                     equ  75
NR_getrlimit                     equ  76
NR_getrusage                     equ  77
NR_gettimeofday                  equ  78
NR_settimeofday                  equ  79
NR_getgroups                     equ  80
NR_setgroups                     equ  81
NR_select                        equ  82
NR_symlink                       equ  83
NR_oldlstat                      equ  84
NR_readlink                      equ  85
NR_uselib                        equ  86
NR_swapon                        equ  87
NR_reboot                        equ  88
NR_readdir                       equ  89
NR_mmap                          equ  90
NR_munmap                        equ  91
NR_truncate                      equ  92
NR_ftruncate                     equ  93
NR_fchmod                        equ  94
NR_fchown                        equ  95
NR_getpriority                   equ  96
NR_setpriority                   equ  97
NR_profil                        equ  98
NR_statfs                        equ  99
NR_fstatfs                       equ  100
NR_ioperm                        equ  101
NR_socketcall                    equ  102
NR_syslog                        equ  103
NR_setitimer                     equ  104
NR_getitimer                     equ  105
NR_stat                          equ  106
NR_lstat                         equ  107
NR_fstat                         equ  108
NR_olduname                      equ  109
NR_iopl                          equ  110
NR_vhangup                       equ  111
NR_idle                          equ  112
NR_vm86old                       equ  113
NR_wait4                         equ  114
NR_swapoff                       equ  115
NR_sysinfo                       equ  116
NR_ipc                           equ  117
NR_fsync                         equ  118
NR_sigreturn                     equ  119
NR_clone                         equ  120
NR_setdomainname                 equ  121
NR_uname                         equ  122
NR_modify_ldt                    equ  123
NR_adjtimex                      equ  124
NR_mprotect                      equ  125
NR_sigprocmask                   equ  126
NR_create_module                 equ  127
NR_init_module                   equ  128
NR_delete_module                 equ  129
NR_get_kernel_syms               equ  130
NR_quotactl                      equ  131
NR_getpgid                       equ  132
NR_fchdir                        equ  133
NR_bdflush                       equ  134
NR_sysfs                         equ  135
NR_personality                   equ  136
NR_afs_syscall                   equ  137
NR_setfsuid                      equ  138
NR_setfsgid                      equ  139
NR__llseek                       equ  140
NR_getdents                      equ  141
NR__newselect                    equ  142
NR_flock                         equ  143
NR_msync                         equ  144
NR_readv                         equ  145
NR_writev                        equ  146
NR_getsid                        equ  147
NR_fdatasync                     equ  148
NR__sysctl                       equ  149
NR_mlock                         equ  150
NR_munlock                       equ  151
NR_mlockall                      equ  152
NR_munlockall                    equ  153
NR_sched_setparam                equ  154
NR_sched_getparam                equ  155
NR_sched_setscheduler            equ  156
NR_sched_getscheduler            equ  157
NR_sched_yield                   equ  158
NR_sched_get_priority_max        equ  159
NR_sched_get_priority_min        equ  160
NR_sched_rr_get_interval         equ  161
NR_nanosleep                     equ  162
NR_mremap                        equ  163
NR_setresuid                     equ  164
NR_getresuid                     equ  165
NR_vm86                          equ  166
NR_query_module                  equ  167
NR_poll                          equ  168
NR_nfsservctl                    equ  169
NR_setresgid                     equ  170
NR_getresgid                     equ  171
NR_prctl                         equ  172
NR_rt_sigreturn                  equ  173
NR_rt_sigaction                  equ  174
NR_rt_sigprocmask                equ  175
NR_rt_sigpending                 equ  176
NR_rt_sigtimedwait               equ  177
NR_rt_sigqueueinfo               equ  178
NR_rt_sigsuspend                 equ  179
NR_pread64                       equ  180
NR_pwrite64                      equ  181
NR_chown                         equ  182
NR_getcwd                        equ  183
NR_capget                        equ  184
NR_capset                        equ  185
NR_sigaltstack                   equ  186
NR_sendfile                      equ  187
NR_getpmsg                       equ  188
NR_putpmsg                       equ  189
NR_vfork                         equ  190
NR_ugetrlimit                    equ  191
NR_mmap2                         equ  192
NR_truncate64                    equ  193
NR_ftruncate64                   equ  194
NR_stat64                        equ  195
NR_lstat64                       equ  196
NR_fstat64                       equ  197
NR_lchown32                      equ  198
NR_getuid32                      equ  199
NR_getgid32                      equ  200
NR_geteuid32                     equ  201
NR_getegid32                     equ  202
NR_setreuid32                    equ  203
NR_setregid32                    equ  204
NR_getgroups32                   equ  205
NR_setgroups32                   equ  206
NR_fchown32                      equ  207
NR_setresuid32                   equ  208
NR_getresuid32                   equ  209
NR_setresgid32                   equ  210
NR_getresgid32                   equ  211
NR_chown32                       equ  212
NR_setuid32                      equ  213
NR_setgid32                      equ  214
NR_setfsuid32                    equ  215
NR_setfsgid32                    equ  216
NR_pivot_root                    equ  217
NR_mincore                       equ  218
NR_madvise                       equ  219
NR_getdents64                    equ  220
NR_fcntl64                       equ  221
NR_gettid                        equ  224
NR_readahead                     equ  225
NR_setxattr                      equ  226
NR_lsetxattr                     equ  227
NR_fsetxattr                     equ  228
NR_getxattr                      equ  229
NR_lgetxattr                     equ  230
NR_fgetxattr                     equ  231
NR_listxattr                     equ  232
NR_llistxattr                    equ  233
NR_flistxattr                    equ  234
NR_removexattr                   equ  235
NR_lremovexattr                  equ  236
NR_fremovexattr                  equ  237
NR_tkill                         equ  238
NR_sendfile64                    equ  239
NR_futex                         equ  240
NR_sched_setaffinity             equ  241
NR_sched_getaffinity             equ  242
NR_set_thread_area               equ  243
NR_get_thread_area               equ  244
NR_io_setup                      equ  245
NR_io_destroy                    equ  246
NR_io_getevents                  equ  247
NR_io_submit                     equ  248
NR_io_cancel                     equ  249
NR_fadvise64                     equ  250
NR_exit_group                    equ  252
NR_lookup_dcookie                equ  253
NR_epoll_create                  equ  254
NR_epoll_ctl                     equ  255
NR_epoll_wait                    equ  256
NR_remap_file_pages              equ  257
NR_set_tid_address               equ  258
NR_timer_create                  equ  259
NR_timer_settime                 equ  260
NR_timer_gettime                 equ  261
NR_timer_getoverrun              equ  262
NR_timer_delete                  equ  263
NR_clock_settime                 equ  264
NR_clock_gettime                 equ  265
NR_clock_getres                  equ  266
NR_clock_nanosleep               equ  267
NR_statfs64                      equ  268
NR_fstatfs64                     equ  269
NR_tgkill                        equ  270
NR_utimes                        equ  271
NR_fadvise64_64                  equ  272
NR_vserver                       equ  273
NR_mbind                         equ  274
NR_get_mempolicy                 equ  275
NR_set_mempolicy                 equ  276
NR_mq_open                       equ  277
NR_mq_unlink                     equ  278
NR_mq_timedsend                  equ  279
NR_mq_timedreceive               equ  280
NR_mq_notify                     equ  281
NR_mq_getsetattr                 equ  282
NR_kexec_load                    equ  283
NR_waitid                        equ  284
NR_add_key                       equ  286
NR_request_key                   equ  287
NR_keyctl                        equ  288
NR_ioprio_set                    equ  289
NR_ioprio_get                    equ  290
NR_inotify_init                  equ  291
NR_inotify_add_watch             equ  292
NR_inotify_rm_watch              equ  293
NR_migrate_pages                 equ  294
NR_openat                        equ  295
NR_mkdirat                       equ  296
NR_mknodat                       equ  297
NR_fchownat                      equ  298
NR_futimesat                     equ  299
NR_fstatat64                     equ  300
NR_unlinkat                      equ  301
NR_renameat                      equ  302
NR_linkat                        equ  303
NR_symlinkat                     equ  304
NR_readlinkat                    equ  305
NR_fchmodat                      equ  306
NR_faccessat                     equ  307
NR_pselect6                      equ  308
NR_ppoll                         equ  309
NR_unshare                       equ  310
NR_set_robust_list               equ  311
NR_get_robust_list               equ  312
NR_splice                        equ  313
NR_sync_file_range               equ  314
NR_tee                           equ  315
NR_vmsplice                      equ  316
NR_move_pages                    equ  317
NR_getcpu                        equ  318
NR_epoll_pwait                   equ  319
NR_utimensat                     equ  320
NR_signalfd                      equ  321
NR_timerfd_create                equ  322
NR_eventfd                       equ  323
NR_fallocate                     equ  324
NR_timerfd_settime               equ  325
NR_timerfd_gettime               equ  326
NR_signalfd4                     equ  327
NR_eventfd2                      equ  328
NR_epoll_create1                 equ  329
NR_dup3                          equ  330
NR_pipe2                         equ  331
NR_inotify_init1                 equ  332
NR_preadv                        equ  333
NR_pwritev                       equ  334
NR_rt_tgsigqueueinfo             equ  335
NR_perf_event_open               equ  336
NR_recvmmsg                      equ  337
NR_fanotify_init                 equ  338
NR_fanotify_mark                 equ  339
NR_prlimit64                     equ  340
NR_name_to_handle_at             equ  341
NR_open_by_handle_at             equ  342
NR_clock_adjtime                 equ  343
NR_syncfs                        equ  344
NR_sendmmsg                      equ  345
NR_setns                         equ  346
NR_process_vm_readv              equ  347
NR_process_vm_writev             equ  348
NR_kcmp                          equ  349
NR_finit_module                  equ  350
NR_sched_setattr                 equ  351
NR_sched_getattr                 equ  352
NR_renameat2                     equ  353
NR_seccomp                       equ  354
NR_getrandom                     equ  355
NR_memfd_create                  equ  356
NR_bpf                           equ  357
NR_execveat                      equ  358
NR_socket                        equ  359
NR_socketpair                    equ  360
NR_bind                          equ  361
NR_connect                       equ  362
NR_listen                        equ  363
NR_accept4                       equ  364
NR_getsockopt                    equ  365
NR_setsockopt                    equ  366
NR_getsockname                   equ  367
NR_getpeername                   equ  368
NR_sendto                        equ  369
NR_sendmsg                       equ  370
NR_recvfrom                      equ  371
NR_recvmsg                       equ  372
NR_shutdown                      equ  373
NR_userfaultfd                   equ  374
NR_membarrier                    equ  375
NR_mlock2                        equ  376
NR_copy_file_range               equ  377
NR_preadv2                       equ  378
NR_pwritev2                      equ  379
NR_pkey_mprotect                 equ  380
NR_pkey_alloc                    equ  381
NR_pkey_free                     equ  382
NR_statx                         equ  383
NR_arch_prctl                    equ  384
NR_io_pgetevents                 equ  385
NR_rseq                          equ  386
NR_semget                        equ  393
NR_semctl                        equ  394
NR_shmget                        equ  395
NR_shmctl                        equ  396
NR_shmat                         equ  397
NR_shmdt                         equ  398
NR_msgget                        equ  399
NR_msgsnd                        equ  400
NR_msgrcv                        equ  401
NR_msgctl                        equ  402
NR_clock_gettime64               equ  403
NR_clock_settime64               equ  404
NR_clock_adjtime64               equ  405
NR_clock_getres_time64           equ  406
NR_clock_nanosleep_time64        equ  407
NR_timer_gettime64               equ  408
NR_timer_settime64               equ  409
NR_timerfd_gettime64             equ  410
NR_timerfd_settime64             equ  411
NR_utimensat_time64              equ  412
NR_pselect6_time64               equ  413
NR_ppoll_time64                  equ  414
NR_io_pgetevents_time64          equ  416
NR_recvmmsg_time64               equ  417
NR_mq_timedsend_time64           equ  418
NR_mq_timedreceive_time64        equ  419
NR_semtimedop_time64             equ  420
NR_rt_sigtimedwait_time64        equ  421
NR_futex_time64                  equ  422
NR_sched_rr_get_interval_time64  equ  423
NR_pidfd_send_signal             equ  424
NR_io_uring_setup                equ  425
NR_io_uring_enter                equ  426
NR_io_uring_register             equ  427
NR_open_tree                     equ  428
NR_move_mount                    equ  429
NR_fsopen                        equ  430
NR_fsconfig                      equ  431
NR_fsmount                       equ  432
NR_fspick                        equ  433
NR_pidfd_open                    equ  434
NR_clone3                        equ  435
NR_close_range                   equ  436
NR_openat2                       equ  437
NR_pidfd_getfd                   equ  438
NR_faccessat2                    equ  439
NR_process_madvise               equ  440
NR_epoll_pwait2                  equ  441
NR_mount_setattr                 equ  442
NR_quotactl_fd                   equ  443
NR_landlock_create_ruleset       equ  444
NR_landlock_add_rule             equ  445
NR_landlock_restrict_self        equ  446
NR_memfd_secret                  equ  447
NR_process_mrelease              equ  448
NR_futex_waitv                   equ  449
NR_set_mempolicy_home_node       equ  450
NR_cachestat                     equ  451
NR_fchmodat2                     equ  452
NR_map_shadow_stack              equ  453
NR_futex_wake                    equ  454
NR_futex_wait                    equ  455
NR_futex_requeue                 equ  456
NR_statmount                     equ  457
NR_listmount                     equ  458
NR_lsm_get_self_attr             equ  459
NR_lsm_set_self_attr             equ  460
NR_lsm_list_modules              equ  461
%endif
